### PR TITLE
PSX Merge 2

### PR DESCRIPTION
**Pull request by apexad**

### CODE REVIEW

**Comment by appletv4** [comment]
Hey did you ever get this working ? PlayStation one games

**Comment by apexad** [comment]
No, this core is too old to be integrated into what Provenance is now,  I got RetroArch working on my own phone and stopped working on trying to bring psx into Provenance, sorry.

**Comment by appletv4** [comment]
Do you have an Apple TV 4? would it be possible to get retroarch working on ATV4

**Comment by apexad** [comment]
I do not yet have an Apple TV 4, sorry.

**Pull request closed without merging**
